config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  get 'text_file/index'
  resources :code_downloads
  resources :filters

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code_download.rb
class CodeDownload < ApplicationRecord
	has_one_attached :file
end

app/models/filter.rb
class Filter < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 60}
    validates :function_name, presence: true, length: {minimum: 3, maximum: 60}
    validates :num_parameters, numericality: {greater_than_or_equal_to: 0}
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/code_downloads_controller.rb
class CodeDownloadsController < ApplicationController
  before_action :set_code_download, only: [:show, :edit, :update, :destroy]

  # GET /code_downloads
  # GET /code_downloads.json
  def index
    @code_downloads = CodeDownload.all
    respond_to do |format|
     format.html {render :index}
     format.json {render :index, status: :ok}
     format.xml {render xml: @code_downloads.as_json}
    end
  end

  # GET /code_downloads/1
  # GET /code_downloads/1.json
  def show
  end

  # GET /code_downloads/new
  def new
    @code_download = CodeDownload.new
  end

  # GET /code_downloads/1/edit
  def edit
  end

  # POST /code_downloads
  # POST /code_downloads.json
  def create
    @code_download = CodeDownload.new(code_download_params)

    respond_to do |format|
      if @code_download.save
        format.html { redirect_to @code_download, notice: 'Code download was successfully created.' }
        format.json { render :show, status: :created, location: @code_download }
      else
        format.html { render :new }
        format.json { render json: @code_download.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /code_downloads/1
  # PATCH/PUT /code_downloads/1.json
  def update
    respond_to do |format|
      if @code_download.update(code_download_params)
        format.html { redirect_to @code_download, notice: 'Code download was successfully updated.' }
        format.json { render :show, status: :ok, location: @code_download }
      else
        format.html { render :edit }
        format.json { render json: @code_download.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /code_downloads/1
  # DELETE /code_downloads/1.json
  def destroy
    @code_download.destroy
    respond_to do |format|
      format.html { redirect_to code_downloads_url, notice: 'Code download was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_code_download
      @code_download = CodeDownload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def code_download_params
      params.require(:code_download).permit(:versions, :description, :file)
    end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :set_filter, only: [:show, :edit, :update, :destroy]

  # GET /filters
  # GET /filters.json
  def index
    @filters = Filter.all
    respond_to do |format|
     format.html {render :index}
     format.json {render :index, status: :ok}
     format.xml {render xml: @filters.as_json}
    end
  end

  # GET /filters/1
  # GET /filters/1.json
  def show
  end

  # GET /filters/new
  def new
    @filter = Filter.new
  end

  # GET /filters/1/edit
  def edit
  end

  # POST /filters
  # POST /filters.json
  def create
    @filter = Filter.new(filter_params)

    respond_to do |format|
      if @filter.save
        format.html { redirect_to @filter, notice: 'Filter was successfully created.' }
        format.json { render :show, status: :created, location: @filter }
      else
        format.html { render :new }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filters/1
  # PATCH/PUT /filters/1.json
  def update
    respond_to do |format|
      if @filter.update(filter_params)
        format.html { redirect_to @filter, notice: 'Filter was successfully updated.' }
        format.json { render :show, status: :ok, location: @filter }
      else
        format.html { render :edit }
        format.json { render json: @filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filters/1
  # DELETE /filters/1.json
  def destroy
    @filter.destroy
    respond_to do |format|
      format.html { redirect_to filters_url, notice: 'Filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter
      @filter = Filter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filter_params
      params.require(:filter).permit(:name, :function_name, :description, :num_parameters, :example)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/text_file_controller.rb
class TextFileController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_downloads_helper.rb
module CodeDownloadsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/text_file_helper.rb
module TextFileHelper
end

app/views/code_downloads/_form.html.erb
<%= form_with(model: code_download, local: true) do |form| %>
  <% if code_download.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(code_download.errors.count, "error") %> prohibited this code_download from being saved:</h2>

      <ul>
      <% code_download.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :versions %>
    <%= form.text_field :versions %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/code_downloads/edit.html.erb
<h1>Editing Code Download</h1>

<%= render 'form', code_download: @code_download %>

<%= link_to 'Show', @code_download %> |
<%= link_to 'Back', code_downloads_path %>

app/views/code_downloads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Code Downloads</h1>
<br><br>
<table id ="tableDownload" class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Versions</th>
      <th>Description</th>
      <th></th>
      <th>Download</th>
      <% if signed_in? %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @code_downloads.each do |code_download| %>
      <tr>
        <td><%= code_download.versions %></td>
        <td><%= code_download.description %></td>
        <td><%= link_to 'Show', code_download %></td>
        <td> <%= link_to 'download',code_download.file %></td>
        <% if signed_in? %>
          <td><%= link_to 'Edit', edit_code_download_path(code_download) %></td>
          <td><%= link_to 'Destroy', code_download, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if signed_in? %>
<%= link_to 'New Code Download', new_code_download_path %>
<% end %>

<script>
$(document).ready( function () {
  $('#tableDownload').DataTable();
} );
</script>

app/views/code_downloads/new.html.erb
<h1>New Code Download</h1>

<%= render 'form', code_download: @code_download %>

<%= link_to 'Back', code_downloads_path %>

app/views/code_downloads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Versions:</strong>
  <%= @code_download.versions %>
</p>
<%= link_to 'download',@code_download.file %>
<p>
  <strong>Description:</strong>
  <%= @code_download.description %>
</p>

<%= link_to 'Edit', edit_code_download_path(@code_download) %> |
<%= link_to 'Back', code_downloads_path %>

app/views/filters/_form.html.erb
<%= form_with(model: filter, local: true, :class=>"form-group col-sm-4") do |form| %>
  <% if filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
      <% filter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :function_name %>
    <%= form.text_field :function_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description , class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :num_parameters %>
    <%= form.number_field :num_parameters, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :example %>
    <%= form.text_field :example, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/filters/edit.html.erb
<h1>Editing Filter</h1>

<%= render 'form', filter: @filter %>

<%= link_to 'Show', @filter %> |
<%= link_to 'Back', filters_path %>

app/views/filters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Filters</h1>
<br><br>
<table id ="filterTable" class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Function name</th>
      <th>Description</th>
      <th>Num parameters</th>
      <th>Example</th>
      <th>Details</th>
      <% if signed_in? %>
        <th>Update</th>
        <th>Delete</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @filters.each do |filter| %>
      <tr>
        <td><%= filter.name %></td>
        <td><%= filter.function_name %></td>
        <td><%= filter.description %></td>
        <td><%= filter.num_parameters %></td>
        <td><%= filter.example %></td>
        <td><%= link_to 'Show', filter %></td>
        <% if signed_in? %>
          <td><%= link_to 'Edit', edit_filter_path(filter) %></td>
          <td><%= link_to 'Destroy', filter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if signed_in? %>
<%= link_to 'New Filter', new_filter_path %>
<% end %>
<script>
$(document).ready( function () {
  $('#filterTable').DataTable();
} );
</script>

app/views/filters/new.html.erb
<h1>New Filter</h1>

<%= render 'form', filter: @filter %>

<%= link_to 'Back', filters_path %>

app/views/filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @filter.name %>
</p>

<p>
  <strong>Function name:</strong>
  <%= @filter.function_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @filter.description %>
</p>

<p>
  <strong>Num parameters:</strong>
  <%= @filter.num_parameters %>
</p>

<p>
  <strong>Example:</strong>
  <%= @filter.example %>
</p>

<%= link_to 'Edit', edit_filter_path(@filter) %> |
<%= link_to 'Back', filters_path %>

app/views/home/index.html.erb
<h1>Home</h1>
<br><br>
<div class="row">
  	<div class="col-sm-4 border border-info">
			<label for="selectFilters"><h4 class="text-info">Imagezen</h4></label>
            <div class="border-top">
                <p style="line-height: 1.3090909090909089; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-family: calibri, sans-serif; font-size: 12pt;">The Imagezen is an application that takes an image as input and generates multiple derivative images by using various image transformation and distortion algorithms. OpenCV library was used for the transformation and distortion of images. The user selects a set of transformation functions and distortion algorithms and gives any required parameters. Some function can be repeated with different parameters. As an example, different angles for rotation of image can be requested. The generator produces a set of images (e.g., with each angle of rotation) and then continues to apply the remaining distortions.</span></p>
            <button type="button" class="btn btn-info btn-lg mr-1" onclick="window.location.href = '/about/index';">Learn More</button>
			</div>
  	</div>

	<div class="col-sm-4 border border-info">
    <label ><h4 class="text-info">Download Source Code</h4></label>
    <div class="border-top">
    <p>Download the code for the image generator. You can download the code for the code generator form this website, or you can go to the GitHub page and download the source code to use this application.</p>
    </div>
	<button type="button" class="btn btn-info btn-lg mr-1" onclick="window.location.href = '/code_downloads';">Download</button>
	<br><br>
	</div>
	<div class="col-sm-4 border border-info">
		<h4 class="text-info">Generate Input Text File</h4>
        <div id="text-file-content" class="container border-top">
            <p style="line-height: 1.3090909090909089; margin-top: 0pt; margin-bottom: 0pt; text-align: justify;"><span style="font-size: 12pt; font-family: calibri, sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The image generator takes an input as a text file which contains all the information it needs. The input file must be in a standard format. The text file will contain:</span></p>
            <ul style="margin-top: 0pt; margin-bottom: 0pt;">
            <li style="list-style-type: disc; font-size: 10pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: calibri, sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The image names that must be fed to the generator</span></li>
            <li style="list-style-type: disc; font-size: 10pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: calibri, sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">The number of combinations of filters/functions to be used for the transformations</span></li>
            <li style="list-style-type: disc; font-size: 10pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre;"><span style="font-size: 12pt; font-family: calibri, sans-serif; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">A &nbsp;list of filter/function names with its parameters</span></li>
            </ul>
        </div>
        
		<br>
	<button type="button" class="btn btn-info btn-lg mr-1" onclick="window.location.href = '/text_file/index';" >Generate a Text File</button>
	</div>
</div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="#"><h1>Imagezen</h1></a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav
		barSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" ari
		a-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
		 <li class="nav-item active">
		 	<a class="nav-link navbar-dark" href="/">Home <span class="sr-only">(current)</span></a>
		 </li>
		 <li class="nav-item">
		 	<a class="nav-link navbar-dark" href="/about/index">About</a>
		 </li>
		 <li class="nav-item">
		 	<a class="nav-link navbar-dark" href="/filters">Filters</a>
		 </li>
		 <li class="nav-item">
		 	<a class="nav-link navbar-dark" href="/code_downloads">Download</a>
		 </li>
		 <li class="nav-item dropdown">
			 <a class="nav-link dropdown-toggle navbar-dark" href="#" id="navbarDropdown" role="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			 Resources
			 </a>
			 <div class="dropdown-menu" aria-labelledby="navbarDropdown">
				 <a class="dropdown-item" target="_blank" href="https://github.com/RikeshGVSU/imagezen">GitHub</a>
				 <div class="dropdown-divider"></div>
				 <a class="dropdown-item" href="/text_file/index">Text File Generator</a>
			 </div>
		 </li>
		</ul>
		<% if signed_in? %>
		<div class="text-info">
      	Signed in as: <%= current_user.email %>
  		</div> 
      <%= button_to 'Sign out', sign_out_path, method: :delete , class: "btn btn-outline-success same-line" %>
    <% else %>
	    <%= form_for :session, url: session_path, :html => { :class => 'form-inline' } do |form| %>
	    <div class="form-group mb-2">
		    <%= form.text_field :email, type: 'email', placeholder: 'User Name', class: "form-control" %>
		</div>

		<div class="form-group mx-sm-3 mb-2">
		    <%= form.password_field :password, placeholder: 'Password', class: "form-control" %>
		</div>
		    <%= form.submit :button => "Sign In", class: "btn btn-outline-success same-line"%>
	     <% end %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageGenerator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script> 
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/text_file/index.html.erb
<h1>Generate Input Text File for Imagezen</h1>
<br><br>
<div class="row">
  	<div class="col-sm-4 border border-info">
		<form id="text-file-form" class="form-group">
			<label for="selectFilters"><h4 class="text-danger">Select filters:</h4></label>
			<div class="border-top">
				<p> Select filter you wish to use and give the required parameters.
				You can add multiple filters buy clicking "Add This Function" and selecting another filter</p>
				<select class="form-control" id="selectFilters" >
					<option>Select a function</option>
				</select>
				<div class = "form-group" id = "filter-description"></div>
				<div class = "form-group" id = "num-parameters"></div>
				<div class = "form-group" id = "input-example"></div>
				<div class = "form-group" id = "input-fields"></div>
				<button type="button" class="btn btn-primary btn-lg mr-1" id = "submit-filter-button" onclick="submitTheFilter()" >Add This Function</button>
			</div>
		</form>
		<br><br>
		<p id = "js-message" class="text-primary"></p>
  	</div>

	<div class="col-sm-4 border border-info">
	<form id="text-file-form" class="form-group">
	<label for="selectFilters" ><h4 class="text-danger">Add Image Name:</h4></label>
	<p class="border-top">Please add the names of the images you wish to add. Each image names must be sapareted by "&&"</p>
	<p>Example: image1.jpg && image2.png && image3.jpg</p>
	<input type="text" id="image-names" placeholder="image1.jpg && image2.png" class="form-control">
	<br>
	<label for="selectFilters" ><h4>Add number of filters to be Used:</h4></label>
	<p class="border-top">Please add the number of filters to be used in each image.</p>
	<p>If you wish to use all possible combinations please input "all"</p>
	<input type="text" id="filter-number" placeholder="all" value="all" class="form-control">
	<br>
	<button type="button" class="btn btn-primary btn-lg mr-1" id = "submit-images-button" onclick="submitImages()" >Add these image names</button>
	</form>
	<br><br>
	<p id = "js-message" class="text-primary"></p>
	</div>
	<div class="col-sm-4 border border-info">
		<h4 class="text-danger">Text File Content</h4>
		<div id="text-file-content" class="container border-top"></div>
		<br>
	<button type="button" class="btn btn-primary btn-lg mr-1" id = "generate-text-file" onclick="generateTextFile()" >Generate a Text File</button>
	</div>
</div>
<script type="text/javascript">
		getFilters();
		loadFilterDetails();
	</script>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>